apiVersion: apps/v1
kind: Deployment
metadata:
  name: school-app-prod
  namespace: production
spec:
  replicas: 3
  selector:
    matchLabels:
      app: school-app
      env: production
  template:
    metadata:
      labels:
        app: school-app
        env: production
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/actuator/prometheus"
        prometheus.io/port: "8080"
    spec:
      containers:
        - name: school-app
          image: ${DOCKER_REGISTRY}/${DOCKER_IMAGE_NAME}:latest
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:mysql://${DB_HOST}:3306/school"
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: username
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: password
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
