apiVersion: apps/v1
kind: Deployment
metadata:
  name: school-app-staging
  namespace: staging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: school-app
      env: staging
  template:
    metadata:
      labels:
        app: school-app
        env: staging
    spec:
      containers:
        - name: school-app
          image: ${DOCKER_REGISTRY}/${DOCKER_IMAGE_NAME}:staging
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:mysql://${DB_HOST}:3306/school_staging"
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: username
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: password
            - name: SPRING_PROFILES_ACTIVE
              value: "staging"
